"""add indexes for timestamp, front, location_id filters

Revision ID: 7f961bc874b0
Revises: 62991568ee20
Create Date: 2026-07-07 15:18:00.585279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f961bc874b0'
down_revision: Union[str, None] = '62991568ee20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_locations_front'), 'locations', ['front'], unique=False)
    op.create_index(op.f('ix_message_locations_location_id'), 'message_locations', ['location_id'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index(op.f('ix_message_locations_location_id'), table_name='message_locations')
    op.drop_index(op.f('ix_locations_front'), table_name='locations')
    # ### end Alembic commands ###
